const setFormikValues = (formik, scoreValues) => {
  formik.setFieldValue(
    "qualification",
    scoreValues?.believabilityScores?.qualification?.score
  );
  formik.setFieldValue(
    "professionalExperience",
    scoreValues?.believabilityScores?.professionalExperience?.score
  );
  formik.setFieldValue(
    "socialscore",
    scoreValues?.believabilityScores?.socialscore?.score
  );
  formik.setFieldValue(
    "patents",
    scoreValues?.believabilityScores?.patents?.score
  );
  formik.setFieldValue(
    "presentation",
    scoreValues?.believabilityScores?.whitepaperConferencePresentation?.score
  );
  formik.setFieldValue("blog", scoreValues?.believabilityScores?.blog?.score);
  formik.setFieldValue("design", scoreValues?.reliabilityScores?.design?.score);
  formik.setFieldValue(
    "framework",
    scoreValues?.reliabilityScores?.framework?.score
  );
  formik.setFieldValue("coding", scoreValues?.reliabilityScores?.coding?.score);
  formik.setFieldValue(
    "debugging",
    scoreValues?.reliabilityScores?.debugging?.score
  );
  formik.setFieldValue(
    "architecture",
    scoreValues?.reliabilityScores?.architecture?.score
  );
  formik.setFieldValue(
    "implementation",
    scoreValues?.reliabilityScores?.implementation?.score
  );
  formik.setFieldValue(
    "teamwork",
    scoreValues?.emotionalIntelligencyScores?.teamWork?.score
  );
  formik.setFieldValue(
    "complexityhandling",
    scoreValues?.emotionalIntelligencyScores?.complexityHandling?.score
  );
  formik.setFieldValue(
    "conflictresolution",
    scoreValues?.emotionalIntelligencyScores?.conflictResolution?.score
  );
  formik.setFieldValue(
    "initiative",
    scoreValues?.emotionalIntelligencyScores?.initiative?.score
  );
  formik.setFieldValue(
    "culturalFit",
    scoreValues?.emotionalIntelligencyScores?.culturalFitPresentation?.score
  );
  formik.setFieldValue(
    "communication",
    scoreValues?.emotionalIntelligencyScores?.communication?.score
  );
  formik.setFieldValue(
    "ownership",
    scoreValues?.emotionalIntelligencyScores?.ownership?.score
  );
  formik.setFieldValue(
    "empathy",
    scoreValues?.emotionalIntelligencyScores?.empathy?.score
  );
  formik.setFieldValue(
    "openness",
    scoreValues?.emotionalIntelligencyScores?.openness?.score
  );
  formik.setFieldValue(
    "plagiarism",
    scoreValues?.undesirableScores?.fakeInformation?.score
  );
  formik.setFieldValue(
    "trustissues",
    scoreValues?.undesirableScores?.plagiarism?.score
  );
  formik.setFieldValue(
    "fakeinformation",
    scoreValues?.undesirableScores?.trustIssues?.score
  );
  formik.setFieldValue(
    "qualificationpercent",
    scoreValues?.believabilityScores?.qualification?.percentile
  );
  formik.setFieldValue(
    "professionalExperiencepercent",
    scoreValues?.believabilityScores?.professionalExperience?.percentile
  );
  formik.setFieldValue(
    "socialscorepercent",
    scoreValues?.believabilityScores?.socialScore?.percentile
  );
  formik.setFieldValue(
    "patentspercent",
    scoreValues?.believabilityScores?.patents?.percentile
  );
  formik.setFieldValue(
    "blogpercent",
    scoreValues?.believabilityScores?.blog?.percentile
  );
  formik.setFieldValue(
    "presentationpercent",
    scoreValues?.believabilityScores?.whitepaperConferencePresentation
      ?.percentile
  );
  formik.setFieldValue(
    "designpercent",
    scoreValues?.reliabilityScores?.design?.percentile
  );
  formik.setFieldValue(
    "frameworkpercent",
    scoreValues?.reliabilityScores?.framework?.percentile
  );
  formik.setFieldValue(
    "codingpercent",
    scoreValues?.reliabilityScores?.coding?.percentile
  );
  formik.setFieldValue(
    "debuggingpercent",
    scoreValues?.reliabilityScores?.debugging?.percentile
  );
  formik.setFieldValue(
    "architecturepercent",
    scoreValues?.reliabilityScores?.architecture?.percentile
  );
  formik.setFieldValue(
    "implementationpercent",
    scoreValues?.reliabilityScores?.implementation?.percentile
  );
  formik.setFieldValue(
    "teamworkpercent",
    scoreValues?.emotionalIntelligencyScores?.teamWork?.percentile
  );
  formik.setFieldValue(
    "complexityhandlingpercent",
    scoreValues?.emotionalIntelligencyScores?.complexityHandling?.percentile
  );
  formik.setFieldValue(
    "conflictresolutionpercent",
    scoreValues?.emotionalIntelligencyScores?.conflictResolution?.percentile
  );
  formik.setFieldValue(
    "initiativepercent",
    scoreValues?.emotionalIntelligencyScores?.initiative?.percentile
  );
  formik.setFieldValue(
    "culturalFitpercent",
    scoreValues?.emotionalIntelligencyScores?.culturalFitPresentation
      ?.percentile
  );
  formik.setFieldValue(
    "communicationpercent",
    scoreValues?.emotionalIntelligencyScores?.communication?.percentile
  );
  formik.setFieldValue(
    "ownershippercent",
    scoreValues?.emotionalIntelligencyScores?.ownership?.percentile
  );
  formik.setFieldValue(
    "empathypercent",
    scoreValues?.emotionalIntelligencyScores?.empathy?.percentile
  );
  formik.setFieldValue(
    "opennesspercent",
    scoreValues?.emotionalIntelligencyScores?.openness?.percentile
  );
  formik.setFieldValue(
    "plagiarismpercent",
    scoreValues?.undesirableScores?.plagiarism?.percentile
  );
  formik.setFieldValue(
    "trustissuespercent",
    scoreValues?.undesirableScores?.trustIssues?.percentile
  );
  formik.setFieldValue(
    "fakeinformationpercent",
    scoreValues?.undesirableScores?.fakeInformation?.percentile
  );
  formik.setFieldValue("mainScore", scoreValues?.mainScore);
};

export { setFormikValues };
